CREATE TABLE LISTE(ID INT PRIMARY KEY, TITRE VARCHAR(255), DESCRIPTION VARCHAR(500));
CREATE TABLE ELEMENT(ID INT PRIMARY KEY, TITRE VARCHAR(255), DESCRIPTION VARCHAR(500), DATECREATION DATE, DATEMODIFICATION DATE, IDLISTE INT);

ALTER TABLE ELEMENT ADD CONSTRAINT ELEMENT_IDLISTE_PARENT
  FOREIGN KEY(IDLISTE) REFERENCES LISTE(ID) ON DELETE RESTRICT;